### ISSUE TITLE
sc is looking for a new maintainer

### ISSUE THREAD

**Issue by n-t-roff** [n-t-roff/sc#18]
Since I don't have the time to maintain GitHub projects any more, `sc` could be transferred to a new owner which continues maintenance.

**Comment by berryamin** [comment]
@n-t-roff I'd be very pleased to take over this role.
We have included sc as part of http://github.com/berryfarm/berrymuch, a CLI software suite for BlackBerry 10, so we want sc to live !

**Comment by n-t-roff** [comment]
@ other users: Are there any objections?

**Comment by n-t-roff** [comment]
Hmm, when I have a look at your GitHub account I get the impression that you do or did not do a lot of C or Unix tool development? Would it not be better to live with pull requests for the time being? `sc` could live through that way too. Any reasonable pull request is applied within one day, that is not a problem for me. I just meant that I don't have the time for true own development anymore.

**Comment by berryamin** [comment]
Indeed, I'm not a C coding expert, so if Maintainer means main C developper of the project, my profile don't match this requirement :-)

**Comment by n-t-roff** [comment]
Yes, expert C and `curses` knowledge and very good knowledge of `make`, Unix, utf8, wide chars, `nroff` and manpage macros would be required.

Nevertheless quality pull requests are always possible and applied short-term. So you need not to worry regarding the BlackBerry software suite integration.

**Comment by dtkerns** [comment]
just found this project... I used vc on Unix Sys V r2.1 back in the (19)80s at Bell Labs... I don't have a ton of time, but assuming it's mostly mature I'm willing to assist maintaining it.

**Comment by n-t-roff** [comment]
You really had worked at bell labs... sounds interesting.
I have invited you as contributor, normally you should have full access rights to the repository with it.

**Comment by dtkerns** [comment]
ya ..  I worked there  1986-2002 .. they finally figured out that the 1982
Divestiture ruling was going to bankrupt them :P

if you're interested in the history...
https://www.historyfactory.com/insights/this-month-in-business-history-bell-system/

in 2007 Stephen Colbert did a bit explaining how Cingular became AT&T
Wireless after AT&T's breakup and subsequent mega-mergers. pretty funny if
you can find it

**Comment by n-t-roff** [comment]
Interesting indeed. Thank you for the information.

**Comment by dtkerns** [comment]
greets .. this is an attempt to fix issue  #6 (thought I'd start w/ the
easy one)
I don't want to screw things up w/ my first commit :P

Do you want to try this patch and see how it fairs? (I only tested on Mac
OSX) .. I can test on several flavors of Linux when I get home (currently
on a business trip)

my test:

./configure;make # verify still works in current dir
make clobber; # new target, destroy all built files
mkdir ../sc_build;cd ../sc_build; ../sc/configure; make
make clobber;

if you think it looks ok, I'll commit/push/close issue

**Comment by dtkerns** [comment]
oops .. I didn't realize I've been replying to this thread the whole time. sorry about that

**Comment by n-t-roff** [comment]
Thank you. I did extensive tests on the BSDs and Solaris in the past. I'm not quite sure but I believe the build tool chain had completely been POSIX. The patch looks a little bit GNU dependent. Hopefully we don't break compatibility with systems which have POSIX only tools (e.g. some BSDs). Maybe you could try to commit it and rollback if there are complaints from non-GNU systems.

We should continue the discussion in #6.
