### ISSUE TITLE
Problems compiling in cygwin

### ISSUE THREAD

**Issue by mblahay** [n-t-roff/sc#2]
I am attempting to compile this in cygwin and am encountering issues.  First things first I supposed. Do you know if it is even possible to get this working in cygwin?

$ make
cc    -Wall -Wextra  -DDFLT_PAGER=\"less\" -c abbrev.c
In file included from abbrev.c:18:0:
sc.h:72:0: warning: "attr_get" redefined
 #define attr_get(a, p, o) ((void)((a) != 0 && (*(a) = stdscr->_attrs)), \
 ^
In file included from compat.h:9:0,
                 from abbrev.c:17:
/usr/include/curses.h:1227:0: note: this is the location of the previous definition
 #define attr_get(ap,cp,o) wattr_get(stdscr,(ap),(cp),(o))
 ^
cc    -Wall -Wextra   -c cmds.c
In file included from cmds.c:29:0:
sc.h:72:0: warning: "attr_get" redefined
 #define attr_get(a, p, o) ((void)((a) != 0 && (*(a) = stdscr->_attrs)), \
 ^
In file included from compat.h:9:0,
                 from cmds.c:28:
/usr/include/curses.h:1227:0: note: this is the location of the previous definition
 #define attr_get(ap,cp,o) wattr_get(stdscr,(ap),(cp),(o))
 ^
cc    -Wall -Wextra  -c color.c
In file included from color.c:17:0:
sc.h:72:0: warning: "attr_get" redefined
 #define attr_get(a, p, o) ((void)((a) != 0 && (*(a) = stdscr->_attrs)), \
 ^
In file included from compat.h:9:0,
                 from color.c:16:
/usr/include/curses.h:1227:0: note: this is the location of the previous definition
 #define attr_get(ap,cp,o) wattr_get(stdscr,(ap),(cp),(o))
 ^
cc    -Wall -Wextra   -c crypt.c
cc    -Wall -Wextra  -c format.c
In file included from format.c:98:0:
sc.h:72:0: warning: "attr_get" redefined
 #define attr_get(a, p, o) ((void)((a) != 0 && (*(a) = stdscr->_attrs)), \
 ^
In file included from compat.h:9:0,
                 from format.c:97:
/usr/include/curses.h:1227:0: note: this is the location of the previous definition
 #define attr_get(ap,cp,o) wattr_get(stdscr,(ap),(cp),(o))
 ^
cc    -Wall -Wextra  -c frame.c
In file included from frame.c:17:0:
sc.h:72:0: warning: "attr_get" redefined
 #define attr_get(a, p, o) ((void)((a) != 0 && (*(a) = stdscr->_attrs)), \
 ^
In file included from compat.h:9:0,
                 from frame.c:16:
/usr/include/curses.h:1227:0: note: this is the location of the previous definition
 #define attr_get(ap,cp,o) wattr_get(stdscr,(ap),(cp),(o))
 ^
yacc -d gram.y
/cygdrive/c/Program Files (x86)/Git/bin/yacc: line 2: /usr/bin/bison: No such file or directory
make: *** [Makefile:359: gram.c] Error 127

**Comment by n-t-roff** [comment]
I didn't test on cygwin. Normally it should build.

You may need to install yacc or bison. This tool (like the compiler, make(1), etc) is required to build sc.

Could you please run:

make distclean
./configure

and send the file config.log and the first 10 lines of Makefile to my mail address (or include the contents in this issue)?

**Comment by mblahay** [comment]
After installing bison and rerunning the installation steps, it worked. Thanks for the help, and now you can say that it works with Cygwin!

**Comment by n-t-roff** [comment]
Thank you too! Nevertheless there is this attr_get warning, which could be debugged. But it makes sense indeed, that I install cygwin too now...
