### ISSUE TITLE
Collaborate/merge with SCIM

### ISSUE THREAD

**Issue by poetaman** [n-t-roff/sc#20]
Hi there, 

[SCIM (SC IMproved)](https://github.com/andmarti1424/sc-im) is looking for collaborators. Please leave a comment on https://github.com/andmarti1424/sc-im/issues/421, if it is something that you would like to. They don't have mouse support like you have enabled in your SC codebase, though they have a nice tightly-coupled lua interface which yours doesn't. And there are some bugs there, like https://github.com/andmarti1424/sc-im/issues/497 which your code base does not (I opened same .sc file in your program and it works well). Please consider helping, I do not know C so have offered to help in other ways.

Thanks!

**Comment by n-t-roff** [comment]
Unfortunately I don't have the time either, even not in the `sc` project here, see issue #18. (By #18 I mean someone of course how has deep knowledge of _all_ software techniques used in this project and who will lead this project in a good manner.)

**Comment by Arumes** [comment]
Do we need to keep this issue open? I think the request is answered with a clear "no". As the issue itself already suggests the projects drifted apart quite a bit, making collaboration too difficult and time consuming.

**Comment by Arumes** [comment]
@dtkerns can you close this one? It's not an issue with sc anyway, just a request which is already answered.
