### ISSUE TITLE
configure file not working for make

### ISSUE THREAD

**Issue by cmdarrah** [n-t-roff/sc#22]
I'm trying to compile sc on Fedora 35 linux after installing gcc and git and making a copy of the repository
What am I not getting? Do I need to make changes to the configure file?

$ ./configure
Checking for make(1) ... yes
Checking for -ffloat-store ... yes
Checking for strlcpy(3) ... no
Checking for strlcat(3) ... no
Checking for -lncursesw ... no
Checking for -lncurses ... no
Checking for -lcurses ... no
Checking for wins_wch(3) ... no
Checking for keyname(3) ... no
Checking for isfinite(3) ... no
Checking for finite(3) ... no
Checking for sc(1) attr_get(3) ... no
Checking for <stdbool.h> ... no

**Comment by karawitan** [comment]
You probably need to add the Development Libraries

`sudo dnf groupinstall "Development Libraries"`

https://unix.stackexchange.com/questions/1338/what-is-the-fedora-equivalent-of-the-debian-build-essential-package

**Comment by Arumes** [comment]
@cmdarrah Are you still around? Did Karawitan's suggestion solve your issue, do you still have problems, are you even still interested? I'm trying to get as many issues closed as possible, clean this project up a bit. :-)

**Comment by Arumes** [comment]
@dtkerns 3rd and last tag for today. 🙂 If the OP can't be bothered to follow up on this issue, I think we can close it.

Maintainers (with enough time/motivation) for sc are hard to find, I'd say we remove as much clutter as possible to make a transfer to a new maintainer less time consuming.
