### ISSUE TITLE
Increase buffer size of sc

### ISSUE THREAD

**Issue by mschuene7** [n-t-roff/sc#26]
I have written a converter for output of a Db2 command line output into `sc` to have the output in a range with fixed header line, and fixed columns. I thereby noticed a limit of ~1000 chars for a field.

To get around this, I changed `sc.h` from
```
#define       FBUFLEN       1024    /* buffer size for a single field */
```
to
```
#ifndef FBUFLEN
#  define        FBUFLEN 1024    /* buffer size for a single field */
#endif
```
and inserted into the `Makefile` the following lines.
```
# buffer size of a single field. It defines the max string length that sc can process.
# The default size is 1024.
FBUF=-DFBUFLEN=10240
#FBUF=
```
With an additional change in the `Makefile` of
```
_CFLAGS= $(CPPFLAGS) $(CFLAGS) $(INCDIR_CURSES) $(DEFINES) $(__CDBG) $(__CLDBG) \
        #-DTRACE='"/tmp/trace.txt"'

```
to
```
_CFLAGS= $(CPPFLAGS) $(CFLAGS) $(INCDIR_CURSES) $(DEFINES) $(FBUF) $(__CDBG) $(__CLDBG) \
        #-DTRACE='"/tmp/trace.txt"'

```
I could create an `sc` version being able to handle 10k size fields. 

When `sc` was published first time back in the 80's I think a 1024 byte field length appeared to be more than enough. Can that be generally increased for nowadays users ?

I might be even better to have the field length adjustable via cmd line parameter. However, when attempting to do that I quickly realised that this requires to dig a bit deeper. I changed all the `sizeof` operators, and declarations of `field[FBUFLEN]` (which will not work for a size value that is not known at compile time). However, it seems this still requires additional changes that I had to postpone for now.

I have modified sc.h and the Makefile templates ... the patch contains the changes.
[sc10240.patch.gz](https://github.com/n-t-roff/sc/files/10435173/sc10240.patch.gz)

**Comment by dtkerns** [comment]
hi sorry for the delay, I'm currently on business travel.  I applied your patch on a fresh clone on my macbook, but it segv'd when I tried to run it, so I didn't immediately pull the change. I'd like to take a closer look at it when I return home this weekend.

**Comment by mschuene7** [comment]
thanks ... basically, I just changed FBUFLEN which is default 1024. I tested / used it on Linux F37.

**Comment by Arumes** [comment]
Seeing that the [pull request](https://github.com/n-t-roff/sc/pull/27) was merged into master over a year ago, and indeed the current version has a FBUFLEN of 10240, I suppose this issue can be closed?

**Comment by dtkerns** [comment]
done
