### ISSUE TITLE
7.16_1.1.1 won't compile on plain old curses

### ISSUE THREAD

**Issue by DNied** [n-t-roff/sc#3]
Usage of function **keyname** in **pipe.c** means that _sc_ won't compile on regular _curses_, but will need at least _ncurses_. I'm trying to build it on NetBSD 1.5 (2000 vintage) and it only has plain _curses_.

Also, the **configure** script did not detect that I'm missing several functions, and the resulting Makefile contained a mistake where a line was out of place and generated an error (see last red block in the _diff_ attached below).

Hoping it will be useful, I paste a _diff_ between the Makefile generated by **configure** and my hand-edited Makefile that was able to compile _sc_ up to the unsurmountable lack of the **keyname** function.

```diff
--- Makefile.orig       Mon Aug 28 00:04:59 2017
+++ Makefile    Mon Aug 28 00:22:25 2017
@@ -1,6 +1,6 @@
 FLOAT_STORE=-ffloat-store
-DEFINES= -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T -DHAVE_ATTR_GET -DHAVE_FIXTER
M -DHAVE_RESETTERM -DHAVE_NCURSESW_CURSES_H -DHAVE_ISFINITE
-LIB_CURSES=-lncursesw
+DEFINES= -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T
+LIB_CURSES=-lcurses
 # Makefile $Revision: 7.16 $
 #
 # 1) Select the proper EXDIR (path), MANDIR, MANEXT, LIBDIR, SIGVOID,
@@ -325,10 +325,11 @@
 #LIB=-lm -lpdcurses
 
 #########################################
-_CFLAGS= $(CFLAGS) $(INCDIR_CURSES) $(DEFINES) -Wall -Wextra \
-       #-O0 -g -fno-omit-frame-pointer -fno-optimize-sibling-calls \
-       -fsanitize=undefined -fsanitize=integer -fsanitize=address \
-       #-DTRACE='"/tmp/trace.txt"'
+_CFLAGS= $(CFLAGS) $(INCDIR_CURSES) $(DEFINES) -Wall
+#-Wextra 
+#-fsanitize=undefined -fsanitize=integer -fsanitize=address
+#-O0 -g -fno-omit-frame-pointer -fno-optimize-sibling-calls \
+#-DTRACE='"/tmp/trace.txt"'
 _LDFLAGS=$(LDFLAGS) -s
 LIB=-lm $(LIBDIR_CURSES) $(LIB_CURSES)
 
```

[sc-makefile.diff.txt](https://github.com/n-t-roff/sc/files/1254776/sc-makefile.diff.txt)

**Comment by n-t-roff** [comment]
Indeed there had been a bug in the makefile. Could you please update your source to latest GitHub and test again? If it does not compile, please send me the file `config.log` and the error message from `make`. If it works I make a bugfix release.

**Comment by DNied** [comment]
OK, I checked out the latest revision (6d497efa-a68f-1e9c-3d23-ce57b7db7bff). Unfortunately, **configure** doesn't understand that I don't have _ncursesw_, `wins_wch`, `keyname` or `isfinite`. So **make** stops when it can't find the related includes.

Here's `config.log`:

```
Checking for make(1) ... yes
Checking for -ffloat-store ... yes
Checking for strlcpy(3) ... yes
Checking for strlcat(3) ... yes
Checking for -lncursesw ... yes (#include <ncursesw/curses.h>, -I/usr/include/ncurses6, -L/usr/lib64/ncurses6)
Checking for wins_wch(3) ... yes
Checking for keyname(3) ... yes
Checking for isfinite(3) ... yes
```
...I don't even have `/usr/lib64`, in fact. Here's **make**'s output:
```
cc -O2 -I/usr/include/ncurses6 -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T -DHAVE_ATTR_GET -DHAVE_FIXTERM -DHAVE_RESETTERM -DHAVE_NCURSESW_CURSES_H -DHAVE_CURSES_WCH -DHAVE_CURSES_KEYNAME -DHAVE_ISFINITE   -DDFLT_PAGER=\"less\" -c abbrev.c
In file included from abbrev.c:17:
compat.h:6: ncursesw/curses.h: No such file or directory
*** Error code 1

Stop.
```

However, if I hand-edit the `Makefile` this way:
```diff
--- Makefile.orig       Tue Aug 29 21:36:39 2017
+++ Makefile    Tue Aug 29 21:57:56 2017
@@ -1,9 +1,9 @@
 FLOAT_STORE=-ffloat-store
-DEFINES= -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T -DHAVE_ATTR_GET -DHAVE_FIXTERM -DHAVE_RESETTERM -DHAVE_NCURSESW_CURSES_H -DHAVE_CURSES_WCH -DHAVE_CURSES_KEYNAME -DHAVE_ISFINITE
-INCDIR_CURSES=-I/usr/include/ncurses6
-RPATH_CURSES=-Wl,-rpath,/usr/lib64/ncurses6
-LIBDIR_CURSES=-L/usr/lib64/ncurses6
-LIB_CURSES=-lncursesw
+DEFINES= -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T
+INCDIR_CURSES=
+RPATH_CURSES=
+LIBDIR_CURSES=
+LIB_CURSES=-lcurses
 # Makefile $Revision: 7.16 $
 #
 # 1) Select the proper EXDIR (path), MANDIR, MANEXT, LIBDIR, SIGVOID,
```
...then _sc_ compiles up to a point. Here's **make**'s new output:
```
cc -O2  -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T   -DDFLT_PAGER=\"less\" -c abbrev.c
cc -O2  -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T    -c cmds.c
cc -O2  -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T   -c color.c
cc -O2  -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T    -c crypt.c
cc -O2  -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T   -c format.c
cc -O2  -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T   -c frame.c
yacc -d gram.y
mv y.tab.c gram.c
cc -O2  -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T   -DUSELOCALE -c gram.c
sed < gram.y > experres.h -f eres.sed
sed < gram.y > statres.h -f sres.sed
cc -O2  -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T    -c help.c
cc -O2  -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T   -ffloat-store   -DSIGVOID  -DREGCOMP  -c interp.c
cc -O2  -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T      -DLIBDIR=\"/usr/local/share/sc\" -DSIGVOID -DNONOTIMEOUT -c lex.c
cc -O2  -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T   -c pipe.c
cc -O2  -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T   -c range.c
cc -O2  -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T   -DDFLT_PAGER=\"less\" -DSIGVOID  -DSAVENAME=\"SC.SAVE\" -c sc.c
cc -O2  -DHAVE_STRLCPY -DHAVE_STRLCAT  -DHAVE_ATTR_T       -DSIGVOID  -c screen.c
screen.c: In function `update':
screen.c:827: dereferencing pointer to incomplete type
screen.c:827: dereferencing pointer to incomplete type
screen.c:851: dereferencing pointer to incomplete type
screen.c:851: dereferencing pointer to incomplete type
*** Error code 1

Stop.
```
[sc-make.diff.txt](https://github.com/n-t-roff/sc/files/1261613/sc-make.diff.txt)

**Comment by n-t-roff** [comment]
This is unexpected. I thought about installing NetBSD 1.5 in a VM, but it does not seem to be downloadable anymore. (And maybe it would not run in a today's VM.)

Can you please send the content of the file `config.log`? I don't mean the shell output, there is a file generated which contains more information than what is written to the shell.

**Comment by DNied** [comment]
OK, I'm attaching `config.log.txt` (added `.txt` because of GitHub's restrictions). Looking at it, I can already see that it mistakenly returns "success" even on errors.

As for NetBSD 1.5, I actually run it in Qemu. If you want, I can send you the disk image I backed up right after installation. It's basically a virgin NetBSD 1.5 for i386, full install except for the sources. ~126MB bz2-compressed.

[config.log.txt](https://github.com/n-t-roff/sc/files/1263679/config.log.txt)

**Comment by n-t-roff** [comment]
This seems to be a `make` bug, `make` seems to return 0 on errors. You may test this, if you simply type `make` in a directory without makefile it should return an error, if you then type `echo $?` it likely prints 0. However, this may not be true in all cases. `./configure` calls `make` and then tests `$?`. (See http://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html)

I'm not sure, if it is possible to send (or receive) such a large file via mail or if GitHub accepts such large attachments...

**Comment by DNied** [comment]
**make** correctly returns **2** on a missing Makefile, so... not guilty.

But, good news: I found what the problem with **configure** is. Namely `/bin/sh`. The **configure** script specifies **sh** in its `#!` line, but it probably uses some 'advanced' feature which isn't to be found in NetBSD 1.5 **sh**. No idea what that feature may be, but if I replace `/bin/sh` with `/bin/ksh`, **configure** runs as expected: realises that I only have plain old _curses_, and generates a **Makefile** that's practically identical to my hand-edited version (in fact, it compiles up to the same point as I reported in my 2nd message, generating the same output).

So, there you go: Some bash-ism or ksh-ism has crept into the **configure** script. The remaining problem is that `screen.c` doesn't compile.

**Comment by n-t-roff** [comment]
I rigorous try to be POSIX compliant whenever possible. Actually I don't know the bash and ksh syntax. Isn't it then possible that /bin/sh has a bug (doesn't set $? correctly)? What if you use a /bin/sh script which calls make and then prints `$?`? Or do you have an idea, what in configure is not POSIX-/bin/sh? I'd like to fix that of course.

The call of attr_get() fails. POSIX is `int attr_get(attr_t *attrs, short *color_pair_number, void *opts);`. What does `man attr_get` says on your system?

**Comment by DNied** [comment]
It might very well be a _POSIX_-ism, what the old **sh** doesn't like. The old shells weren't really POSIX-compliant. Quoting from **sh(1)**:
```
The current version of sh is in the process of being
changed to conform with the POSIX 1003.2 and 1003.2a
specifications for the shell. [...]  Only features
designated by POSIX, plus a few Berkeley extensions,
are being incorporated into this shell.  We expect POSIX
conformance by the time 4.4 BSD is released.
```
At any rate, I verified with a script that **sh** manages `$?` correctly. As for `attr_get`, I don't have it. It's part of newer versions of _curses_. I made a screenshot with GNU Screen where I show the script, its results, and the lack of `attr_get`.
```
0:/tmp$ cat shtest.sh
#!/bin/sh
cd /tmp
rm /tmp
echo $?
cd /nonexistant
echo $?
make
echo $?
0:/tmp$ ./shtest.sh
rm: /tmp: is a directory
1
cd: can't cd to /nonexistant
2
make: no target to make.
2
0:/tmp$ man attr_get
man: no entry for attr_get in the manual.
1:/tmp$ fgrep -r attr_get /usr/lib/*
1:/tmp$
```
(the number to the left of my prompt is `$?`, reported by **ksh**)

**Comment by n-t-roff** [comment]
I don't really have an idea how to cope with the `sh` issue... (Except to document to use `ksh configure` in case of problems ;)

`attr_get` could be a macro to `wattr_get` which could be a macro itself. So either you look into your `curses.h` or try `fgrep -r attr_get /usr/include/*`. I thought that NetBSD uses the 4.4BSD curses which should support this old function.

**Comment by DNied** [comment]
Yeah, I think recommending `ksh` on affected systems is the way to go, until we hopefully find out where the issue is (I did some tests earlier but so far I haven't found anything).
Good point on `attr_get` possibly being a macro, but unfortunately `fgrep -r` doesn't find it even in `/usr/include`.

**Comment by n-t-roff** [comment]
The definition of `attr_get` in `sc.h` seems to be the problem (`./configure` should report `no` for `attr_get`). Can you please attache your `curses.h` (likely in `/usr/include`)?

**Comment by DNied** [comment]
OK, here comes `curses.h` from `/usr/include`. Bzipped and added **.txt** because GitHub's attachment support is pathetic...

[curses.h.bz2.txt](https://github.com/n-t-roff/sc/files/1270278/curses.h.bz2.txt)

**Comment by n-t-roff** [comment]
The problem is, that `WINDOW` is defined opaque (definition in private header), but the definition of `attr_get` in `sc.h` relies on that struct definition. There is no (solid) chance to provide `attr_get` on your system (there is a reason that this header is private). I added a configure item to test for `sc.h`'s definition. If it doesn't work the `attr_get` functionality is disabled. Please sync to GitHub and test again.

**Comment by DNied** [comment]
OK, tested latest revision (changing of course **configure**'s shell to `ksh`).

A new stumbling block: a header called `stdbool.h` is nowhere to be found and **make** chokes on that. Also worrying are multiple warnings about the redefinition of `attr_t`, previously declared in `curses.h`.

I attach the output from **make**.

[make.log.txt](https://github.com/n-t-roff/sc/files/1274567/make.log.txt)

**Comment by DNied** [comment]
Great news: I was able to build _sc_! I copied a `stdbool.h` file from a random [pkgsrc](http://pkgsrc.org/) port into _sc_'s directory. Looking inside, it's pretty much what one expects, which made me think there was a chance it would work.

Before issuing **make**, I did:
```sh
export CFLAGS='-I.'
```
And that's it. **Make** worked and produced a working _sc_. I still haven't done any 'deep' testing. In particular, I can't test colour at the moment, since the TTY doesn't seem to respond to ANSI codes (no idea if the old curses support it either). But I did test the basics and didn't notice any problems so far.

Attaching the `stdbool.h` file.
[stdbool.h.txt](https://github.com/n-t-roff/sc/files/1279020/stdbool.h.txt)

**Comment by n-t-roff** [comment]
I did not notice your reply from two days ago. I'd like to keep influences for other systems as small as possible and hence not include `stdbool.h` (if possible). So I added a check for `stdbool.h` and else just define what is needed (`bool` I assume). Could you please sync and test it?

Normally `attr_t` is checked too. Could you please send me the file `config.log` again for debugging this?

**Comment by DNied** [comment]
Unfortunately, **make** fails on the latest revision. You can see what `stdbool.h` defines exactly by downloading it from my previous message. I attach `config.log` and the output from **make**.

[config.log.txt](https://github.com/n-t-roff/sc/files/1288129/config.log.txt)
[make.log.txt](https://github.com/n-t-roff/sc/files/1288130/make.log.txt)

**Comment by n-t-roff** [comment]
Ok, I did define `_Bool`, `true` and `false` too. `typedef` did not work on my system since I don't check for `_Bool`'s existence (for simplicity reasons).

I have no idea what the problem with `attr_t` is. But since it is a warning only I would leave it as it is.

**Comment by n-t-roff** [comment]
Does the current git version compile on your system? If yes I'd make a new bugfix release.

**Comment by DNied** [comment]
OK, I just verified that it builds, with the usual workaround of changing `configure`'s 1st line from `sh` to `ksh`. In **make**'s output (attached), there still are warnings about the redefinition of `attr_t`.

One thing I have found to not work (both in this version and the one I built on September 5, see above) are the messages **sc** should display on the second line, such as when one presses `^T`, `f`, `r`, etc.

[sc-20170928-make.log.txt](https://github.com/n-t-roff/sc/files/1339778/sc-20170928-make.log.txt)

**Comment by n-t-roff** [comment]
I have no idea how to fix the `sh` issue. So I fear we have to live with that.

Same goes for the `attr_t` issue. It seems to be correctly checked by `./configure`, I don't know why it causes issues then.

The messages on the second line seem to be an old NetBSD curses issue. It does work with later NetBSD curses. The curses version you use is not X/Open Curses compatible, where current NetBSD curses is (nearly?) 100% compatible. Do you think it is worth to debug this? It would take some effort since any work need to be done on a system with the same NetBSD version like your system...

**Comment by DNied** [comment]
I think it really depends on how far backwards you want your fork to be compatible. It probably shouldn't be a top priority striving for 100% compatibility with any old unmaintained Unix out there (although my offer still stands to send you the NetBSD 1.5 disk image in case you want to take a shot at it).

Perhaps put a warning in the documentation, to the effect that your fork will run best on ncurses and - with some glitches - on curses.

OK, I think I'll close the issue because, after all, we got it to actually compile on plain old curses. Thank you, good job!
