### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [n-t-roff/sc#4]
Would you like to add more error handling for return values from functions like the following?
- [fclose](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream") ⇒ [write_hist](https://github.com/n-t-roff/sc/blob/f9c1e628b44be7e32a8dec1cdfaa69bc22b71570/vi.c#L1657)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output") ⇒ [main](https://github.com/n-t-roff/sc/blob/ff0ef06d7b42d41ac64ea19216d1fa4039d1fc88/psc.c#L161)

**Comment by n-t-roff** [comment]
It is not wrong but uncommon to check the return value of printf. Do you assume that this printf causes issues or why would you like to have it checked in this special case?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?
