### ISSUE TITLE
Support for out-of-source builds

### ISSUE THREAD

**Issue by elfring** [n-t-roff/sc#6]
How do you think about to benefit from [parallel build trees](https://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html "Parallel build trees (a.k.a. VPATH builds)") also for this software?
Would you like to [support out-of-source](https://gitlab.kitware.com/cmake/community/wikis/FAQ#what-is-an-out-of-source-build "https://gitlab.kitware.com/cmake/community/wikis/FAQ#what-is-an-out-of-source-build") ([VPATH](https://www.gnu.org/software/make/manual/html_node/General-Search.html "Search path for all prerequisites")) builds?

**Comment by dtkerns** [comment]
continued from #18 .. I've DLed an allegedly POSIX version of make... https://frippery.org/make/ ... it builds, but fails to do basic make functionality. If you happen to have better pointer to POSIX make, please post

**Comment by n-t-roff** [comment]
OK, then lets commit it.

**Comment by rmyorston** [comment]
> it builds, but fails to do basic make functionality

I suppose it depends on your expectation of what constitutes 'basic make functionality'. Strict POSIX make is really very limited compared to any recent implementation.

**Comment by dtkerns** [comment]
I found my issue with the POSIX make (my own dumb mistake, trying to build on OSX)

VPATH is not supported by POSIX make; I do find an XSI extension to POSIX called PROJECTDIR, but it's not supported by frippery's pdpmake and I'm not convinced PROJECTDIR would work as intended (to substitute for GNU make's VPATH) even if it were. So it seems this issue (#6) is at odds w/ the project's commitment to POSIX make. I will attempt to detect support for VPATH by make in the configure script and if support is not there, than out of source builds will not be supported.
