### ISSUE TITLE
-P and -W options don't work because of clearok() call with uninitialised curses

### ISSUE THREAD

**Issue by snarkophilus** [n-t-roff/sc#8]
At least on NetBSD, using the -P or -W command line options cause a seg fault because the clearok() call in main() happens with an uninitialised curses.  Adding a "if (usecurses)" check for clearok() gets things working.

New to github, so instead of a pull request here's a simple patch.  At least it's short :)

```diff
diff --git a/sc.c b/sc.c
index d2a4e1b..e4bacd2 100644
--- a/sc.c
+++ b/sc.c
@@ -395,7 +395,8 @@ main (int argc, char  **argv)
        exit (0);
     }

-    clearok(stdscr, TRUE);
+    if (usecurses)
+       clearok(stdscr, TRUE);
     EvalAll();

     if (mopt)
```

**Comment by n-t-roff** [comment]
Thank you for fixing it.
A pull request is less work in total. Just clone the repo to your account at GitHub, then clone to your computer, do the fix, push to GitHub and do the pull request. I could patch it as well but then it's commited as @n-t-roff and not as @snarkophilus, which might not be what you want.

**Comment by snarkophilus** [comment]
Cool, let me try that out.  Hopefully you'll receive a pull request soon!

**Comment by snarkophilus** [comment]
I hope the two pull requests for both issues I created today worked.

**Comment by n-t-roff** [comment]
Something did went wrong. I reverted it. I'll try to apply the second pull request within 24 h, maybe you need to reopen the first pull request again. I'll inform you.

**Comment by n-t-roff** [comment]
GitHub did use my ID for the commit which never did happen for any pull request merge before. Did you provide an email address for your GitHub account? If not this could be the problem. (https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user)

**Comment by snarkophilus** [comment]
Looks like my email addr was set to private.  Not sure if that was the problem?  Changed that to public now.

**Comment by snarkophilus** [comment]
Did you want me to re-submit the pull request for this one?

**Comment by n-t-roff** [comment]
It seems that you need to re-submit both requests. Lets try it with the first one at first.

**Comment by snarkophilus** [comment]
I think I'm making a nice mess of my fork :).  Will give up for the night and try again tomorrow.

**Comment by snarkophilus** [comment]
Had to try one more time.  Hopefully this one works...

**Comment by n-t-roff** [comment]
It does somehow seem to have worked, although you're not on the contributors list(???). Maybe this is a bug caused by the new Microsoft GitHub ownership....
So lets simply also apply the second pull request (I had deleted it, so please also re-submit it too.).

**Comment by snarkophilus** [comment]
Not too fussed about the contributor bit yet.  Thanks for your help along the way.  git is very different to cvs that I'm used to!

I've hopefully submitted a working pull request for the other change.

**Comment by snarkophilus** [comment]
Issue fixed.
